apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hankki
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/jeon950523/hankki_travel_back
    newName: ghcr.io/jeon950523/hankki_travel_back
    newTag: sha-758c70e2da54b2f1d5933427c489b45691eda25f
