CREATE TABLE nutrition_foods (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source_food_id VARCHAR(100) NOT NULL,
    source_food_name VARCHAR(500) NOT NULL,
    normalized_food_name VARCHAR(300) NOT NULL,
    category VARCHAR(300) NOT NULL,
    reference_basis VARCHAR(20) NOT NULL,
    reference_amount DECIMAL(10,3) NULL,
    reference_unit VARCHAR(10) NOT NULL,
    energy_kcal DECIMAL(12,3) NULL,
    carbohydrate_g DECIMAL(12,3) NULL,
    sugar_g DECIMAL(12,3) NULL,
    protein_g DECIMAL(12,3) NULL,
    fat_g DECIMAL(12,3) NULL,
    sodium_mg DECIMAL(12,3) NULL,
    source_dataset_name VARCHAR(300) NOT NULL,
    source_dataset_version VARCHAR(60) NOT NULL,
    source_institution VARCHAR(300) NOT NULL,
    source_generated_date DATE NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_nutrition_food_source UNIQUE (source_dataset_name, source_dataset_version, source_food_id),
    CONSTRAINT ck_nutrition_food_basis CHECK (reference_basis IN ('100G', '100ML', 'OTHER')),
    CONSTRAINT ck_nutrition_food_unit CHECK (reference_unit IN ('g', 'ml', 'other')),
    CONSTRAINT ck_nutrition_food_active CHECK (active IN (TRUE, FALSE)),
    CONSTRAINT ck_nutrition_food_name CHECK (CHAR_LENGTH(TRIM(normalized_food_name)) > 0),
    INDEX ix_nutrition_foods_normalized_active (normalized_food_name, active),
    INDEX ix_nutrition_foods_dataset_active (source_dataset_name, source_dataset_version, active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE nutrition_import_runs (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source_dataset_name VARCHAR(300) NOT NULL,
    source_dataset_version VARCHAR(60) NOT NULL,
    source_row_count INT NOT NULL,
    imported_count INT NOT NULL,
    excluded_count INT NOT NULL,
    status VARCHAR(30) NOT NULL,
    failure_summary VARCHAR(300) NULL,
    started_at DATETIME(6) NOT NULL,
    completed_at DATETIME(6) NULL,
    CONSTRAINT ck_nutrition_import_counts CHECK (source_row_count >= 0 AND imported_count >= 0 AND excluded_count >= 0),
    CONSTRAINT ck_nutrition_import_status CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    INDEX ix_nutrition_import_runs_source (source_dataset_name, source_dataset_version, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
