apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hankki-travel-api
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: production
            namespace: hankki
  template:
    metadata:
      name: hankki-travel-api-{{environment}}
      labels:
        app.kubernetes.io/part-of: hankki-travel
    spec:
      project: default
      source:
        repoURL: git@github.com:jeon950523/hankki_travel_back.git
        targetRevision: main
        path: k8s/base
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true