apiVersion: v1
kind: ConfigMap
metadata:
  name: hankki-travel-api-config
  labels:
    app.kubernetes.io/name: hankki-travel-api
    app.kubernetes.io/part-of: hankki-travel
data:
  WEB_BASE_URL: https://hankki.kro.kr
  ADMIN_SYNC_ENABLED: "false"