apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hankki
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/jeon950523/hankki_travel_back
    newName: ghcr.io/jeon950523/hankki_travel_back
    newTag: main